name: Copy of Real-time Accelerometer2
description: Real-time Accelerometer data visualization and movement detection using Modulino Movement sensor
ports: []
bricks:
- arduino:web_ui: {}
- arduino:motion_detection: {}
icon: 🐍
